@startuml

package sample <<Folder>>{
package composer <<Folder>>{
class Arrows
class Begin extends Component
class End extends Component
class Solution extends Component
class Operation extends Component
abstract class Component
class ComponentException extends java.lang.Exception
class Composite extends Component
}
class Main extends javafx.application.Application
class Controller implements javafx.fxml.Initializable
}

@enduml